__default__:
    h_vmem: 4G
    h_rt:   1:0:0
    submission_string: " "
    tmem: 4G
subset_bam:
    submission_string: "-pe smp 2 -R y"
    h_vmem:   14G
    tmem:   14G
    h_rt: 24:00:00
index_bam:
    submission_string: ""
    h_vmem:   10G
    tmem:   10G
    h_rt: 24:00:00
