# if you're using a SAF, set to False
gtf_used: True

saf:  tests/reference/annotations.saf

# Path to directory where results should be output (include slash at end)
out_spot: tests/feature_counts


# Dir when bams to quant are stored (include slash at end)
bam_spot: tests/test_data


# Pick out bams from bam_dir with this bam_suffix
# Also used to strip from file to get sample name
# e.g. Cont-B_S2.pass2Aligned.sortedByCoord.out.bam becomes Cont-B_S2
bam_suffix: ".bam"

# Path to GTF file of genes/regions want to quantify
#gtf:  /SAN/vyplab/vyplab_reference_genomes/annotation/human/ensembl/Homo_sapiens.GRCh38.100.gtf
gtf:  tests/reference/annotations.gtf


# What is strandedness of data (super nice guide below)
# https://littlebitofdata.com/en/2017/08/strandness_in_rnaseq/
feature_counts_strand_info: "-s 0"

#"pe" if paired-end data, "se" if single-end data
# if using long read setting (long_reads = True), put se (I think...)
end_type: "pe"

# Count reads at What feature type? (attribute in GTF)
feature_type: "Name"

# Count reads at 'feature' level (each exon) or for whole gene (put sth other than "feature")
count_at: "feature"

# What identifier in GTF to use for constructing meta-features if counting at the gene level
# usually 'gene_id' is best
attribute_type: "Name"

# Use long reads (-L) setting
# True if use, else False
long_reads: False
