
gtf: tests/reference/annotations.gtf

# Whether to generate custom transcriptome fasta (using gffread)
# True or False (no quotes)
generate_fasta: True

# Path to FASTA file of transcript sequences. Ignored if generate_fasta: True
transcripts_fasta: tests/reference/transcripts.fa

# Path to genome sequence FASTA file. Required if generating index from scratch (for decoy sequences/making transcripts fasta)
genome_fasta: tests/reference/genome.fa

# Top level directory storing salmon indices
salmon_index_dir: "tests/salmon_index/"

# Name of subdirectory of salmon_index_dir in which to store/find annotation-specific index
salmon_index_name: gencode_v34

# kmer-size for salmon index (= minimum acceptable length for valid match)
# Default: 31 (recommended for >= 75bp reads)
salmon_kmer_size: 31

# Directory containing input FASTQs
fastq_dir: tests/pulled_fastq
# 'pe' for paired-end and 'se' for single-end
end_type: "pe"
# Suffix to strip from FASTQs in fastq_dir to get sample names
fastq1_suffix: "_1.merged.fastq.gz"

# Suffix for 2nd mate of read pairs. Only used if end_type: pe
fastq2_suffix: "_2.merged.fastq.gz"

# Directory to store Salmon quantifications
out_dir: tests/salmon/

salmon_strand_info: "A"  # automatic detection

# Be sure to update config/cluster.yaml to reflect this
index_threads: 4
quant_threads: 2

# Name of subdirectory of out_dir to store log/stderr files for each rule
logs_dir: single_steps_logs/
